#!/usr/bin/env python3
"""Copy named u8g2 font arrays out of u8g2_fonts.c into a small C header.

    extract_fonts.py u8g2_fonts.c OUT.h NAME [NAME ...]

Each font is a C string literal (octal escapes); it is re-emitted as a
byte array so the host harness can decode it (test/ui/canvas_host.c).
Standard library only.
"""
import re
import sys


def literal_bytes(body):
    out = bytearray()
    for piece in re.findall(r'"((?:[^"\\]|\\.)*)"', body):
        i = 0
        while i < len(piece):
            c = piece[i]
            if c != "\\":
                out.append(ord(c))
                i += 1
                continue
            n = piece[i + 1]
            m = re.match(r"[0-7]{1,3}", piece[i + 1 :])
            if m:
                out.append(int(m.group(0), 8))
                i += 1 + len(m.group(0))
                continue
            simple = {"n": 10, "t": 9, "r": 13, "\\": 92, '"': 34, "'": 39, "?": 63, "a": 7,
                      "b": 8, "f": 12, "v": 11}
            if n in simple:
                out.append(simple[n])
                i += 2
                continue
            raise SystemExit("unsupported escape \\%s" % n)
    return bytes(out)


def main(argv):
    if len(argv) < 4:
        raise SystemExit(__doc__)
    text = open(argv[1], encoding="latin-1").read()
    lines = ["/* Generated by test/ui/extract_fonts.py from the firmware's u8g2_fonts.c. */",
             "#pragma once", "#include <stdint.h>"]
    for name in argv[3:]:
        # The initializer: string literals separated by whitespace, then ';'
        # (a literal may itself contain ';').
        m = re.search(
            r'const uint8_t %s\[(\d+)\][^=]*=((?:\s*"(?:[^"\\]|\\.)*")+)\s*;' % re.escape(name),
            text)
        if not m:
            raise SystemExit("font %s not found" % name)
        data = literal_bytes(m.group(2))
        # The declared size includes the string's terminating NUL.
        if len(data) + 1 != int(m.group(1)):
            raise SystemExit("font %s: %d bytes, declared %s" % (name, len(data), m.group(1)))
        body = ",".join(str(b) for b in data)
        lines.append("static const uint8_t %s[%d] = {%s,0};" % (name, len(data) + 1, body))
    with open(argv[2], "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv)
